# Generated by Django

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('p_totschool_appointment_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
