# Generated by Django

from django.db import migrations, models
import django.utils.timezone

def compute_average_datetime(apps, schema_editor):
    Appointment = apps.get_model('p_totschool_appointment_tracker', 'Appointment')
    for appointment in Appointment.objects.all():
        if appointment.start:
            appointment.datetime = appointment.start
            appointment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('p_totschool_appointment_tracker', '0002_appointment_phone_appointment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(compute_average_datetime, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='appointment',
            name='end',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start',
        ),
    ]
