# Generated by Django 6.0.1 on 2026-02-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p_totschool_appointment_tracker", "0004_appointment_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-datetime"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="generated_letter",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="location",
            field=models.TextField(max_length=250),
        ),
    ]
